# Generated by Django 4.2.4 on 2024-08-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_customuser_location_customuser_is_verified_and_more'),
    ]

    operations = [
    ]
